#!/bin/bash

# Exist command
function exist_command () {
  command -v "$1" >/dev/null 2>&1
}

# Install function
function install() {
  echo "Installing $1"
  if [ "$system_type" = "Darwin" ]; then
    brew install $1
  fi
  if [ "$system_type" = "Linux" ]; then
    sudo apt install $1
  fi
}

# Config fish
function config_fish() {
  echo "Configuring $1"
  if [ "$system_type" = "Darwin" ]; then
    chsh -s /usr/local/bin/fish
  fi
  if [ "$system_type" = "Linux" ]; then
    chsh -s /usr/bin/fish
  fi
}

# Pre-install dependencies in MacOS
function pre_install_mac_os() {
  if ! exist_command brew; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi
  
  for command in curl vim fzf fd bat fish; do
    if ! exist_command $command; then
      install $command
      if [ $command = fish ]; then
        config_fish
      fi
    fi
  done
}

function pre_install_linux() {
  for command in python3-pip curl vim terminator fzf fd-find bat fish; do
    if ! exist_command $command; then
      install $command
      if [$command = fish]; then
        config_fish
      fi
    fi
  done
  
  if exist_command terminator; then
    mkdir -p $HOME/.config/terminator/plugins
    wget https://git.io/v5Zww -O $HOME"/.config/terminator/plugins/terminator-themes.py"
  fi
}

# Bootrsaping plugins (fisher, vim)
function bootstrap_plugins() {
  if [ ! -f "$HOME/.config/fish/functions/fisher.fish" ]; then
    echo "Installing fisher"
    curl -sL https://git.io/fisher | source && \
    	fisher install jorgebucaran/fisher \
    		jethrokuan/z \
		edc/bass \
		jorgebucaran/fish-bax \
		danhper/fish-ssh-agent \
		jorgebucaran/nvm.fish \
		franciscolourenco/done \
		jethrokuan/fzf \
		hauleth/agnoster
  fi

  if [ -f "$HOME/.config/fish/functions/fisher.fish" ]; then
    echo "Bootstraping fisher"
    fish
    fisher update
  fi

  if exist_command vim; then
    echo "Bootstraping vim"
    vim +'PlugInstall --sync' +qa
  fi
}

function start() {
  # Navigate to root of yadm repository.
  cd "$HOME"

  # Set up submodules.
  echo "Initialize submodules"
  yadm submodule update --recursive --init

  # Getting OS
  system_type=$(uname -s)

  if [ "$system_type" = "Darwin" ]; then
    pre_install_mac_os
  fi
  
  if [ "$system_type" = "Linux" ]; then
    pre_install_linux
  fi

  bootstrap_plugins
}

start
