#!/bin/bash

# Exist command
function exist_command () {
  command -v "$1" >/dev/null 2>&1
}

# Install function
function install() {
  echo "Installing $1"
  if [ "$system_type" = "Darwin" ]; then
    brew install $1
  fi
  if [ "$system_type" = "Linux" ]; then
    sudo apt-get install $1
  fi
}

# Config fish
function config_fish() {
  echo "Configuring $1"
  if [ "$system_type" = "Darwin" ]; then
    chsh -s /usr/local/bin/fish
  fi
  if [ "$system_type" = "Linux" ]; then
    chsh -s /usr/bin/fish
  fi
}

# Pre-install dependencies in MacOS
function pre_install_mac_os() {
  if ! exist_command brew; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi

  if ! exist_command curl; then
    brew install curl
  fi

  if ! exist_command vim; then
    install vim
  fi

  if ! exist_command fish; then
    install fish
    config_fish
  fi
}

# Bootrsaping plugins (vim, fisher)
function bootstrap_plugins() {
  if exist_command vim; then
    echo "Bootstraping vim"
    vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
  fi

  if [ ! -f "$HOME/.config/fish/functions/fisher.fish" ]; then
    echo "Installing fisher"
    curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://raw.githubusercontent.com/fisherman/fisherman/master/fisher.fish
    fisher z fzf edc/bass
  fi

  if [ -f "$HOME/.config/fish/functions/fisher.fish" ]; then
    echo "Bootstraping fisher"
    fish
    fisher update
  fi

}

function start() {
  # Navigate to root of yadm repository.
  cd "$HOME"

  # Set up submodules.
  echo "Initialize submodules"
  yadm submodule update --recursive --init

  # Getting OS
  system_type=$(uname -s)

  if [ "$system_type" = "Darwin" ]; then
    pre_install_mac_os
  fi

  if ! exist_command terminator; then
    install terminator
  fi

  if ! exist_command vim; then
    install vim
  fi

  if ! exist_command fish; then
    install fish
    config_fish
  fi

  bootstrap_plugins
}

start
